'\" te
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").  
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\" Copyright (c) 2006, Sun Microsystems, Inc.  All Rights Reserved.
.TH openssl 5 "14 Jun 2006" "SunOS 5.11" "Standards, Environments, and Macros"
.SH NAME
openssl \- OpenSSL cryptographic and Secure Sockets Layer toolkit
.SH DESCRIPTION
.LP
OpenSSL is a cryptography toolkit that implements the Secure Sockets Layer (SSLv2/v3) and Transport Layer Security (TLS v1) network protocols.
.LP
The following features are omitted from the binaries for issues including but not limited to patents, trademark, and US export restrictions: ECC,  IDEA, MDC2, RC3, RC5, Dynamic Engine Loading, 4758_CCA Engine, AEP Engine,  Atalla Engine, CHIL Engine, CSWIFT Engine, GMP Engine, NURON Engine, PadLock
Engine, Sureware Engine, and UBSEC Engine.
.LP
A new PKCS#11 engine has been included with ENGINE name "pkcs11".
.LP
The PKCS#11 engine is configured to use the Solaris Cryptographic Framework. See \fBcryptoadm\fR(1M) for configuration information.
.LP
Due to requirements of the PKCS#11 standard regarding \fBfork\fR(2) behavior, some applications that use the OpenSSL EVP interfaces and \fBfork()\fR with
active crypto contexts might experience unexpected behavior.
.LP
To build an OpenSSL application, use the following \fBcc\fR command line options:
.sp
.in +2
.nf
cc [ \fIflag\fR... ] \fIfile\fR... -I/usr/sfw/include -lcrypto -lssl \e
  -L/usr/sfw/lib -R/usr/sfw/lib [ \fIlibrary\fR... ]
.fi
.in -2

.LP
Extensive additional documentation for OpenSSL modules is available in the \fB/usr/sfw/share/man\fR directory. This documentation can be viewed with \fBman\fR(1)
by including \fB/usr/sfw/share/man\fR in the MANPATH environment variable. Running \fBcatman\fR(1M) on the OpenSSL manual pages is not supported.
.LP
To view the license terms, attribution, and copyright for OpenSSL, see \fB/var/sadm/pkg/SUNWopensslr/install/copyright\fR.
.SH ATTRIBUTES
.LP
See \fBattributes\fR(5) for a description of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
AvailabilitySUNWopensslr, SUNWopenssl
_
Interface StabilityExternal
.TE

.SH SEE ALSO
.LP
\fBcryptoadm\fR(1M), \fBlibpkcs11\fR(3LIB), \fBattributes\fR(5)
.LP
\fB/usr/sfw/man/man1/openssl.1\fR
